Parameters:
  DeploymentPhase:
    Type: "String"
    Default: "Development"
    AllowedValues:
      - "Development"
      - "Beta"
      - "Pre-Production"
      - "Production"
    Description: >
      Deployment phases - 
      Development is for testing changes before commit and stack changes are 
      run manually through Console or CLI; 
      Beta is used for automated testing of changes before committing to main; 
      Pre-Production is verification after pushing to main; 
      Production is the final deployment
Mappings:
  DeploymentPhaseProperties:
    Development:
      ResourceSuffix: "-dev"
    Beta:
      ResourceSuffix: "-beta"
    Pre-Production:
      ResourceSuffix: "-preprod"
    Production:
      ResourceSuffix: ""
Resources:
  DDBPunchClocksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - "PunchClocks${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
      KeySchema:
        - AttributeName: "Owner"
          KeyType: "HASH"
        - AttributeName: "PunchClockName"
          KeyType: "RANGE"
      AttributeDefinitions:
        - AttributeName: "Owner"
          AttributeType: "S"
        - AttributeName: "PunchClockName"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
  DDBPunchClockPropertiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - "PunchClockProperties${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
      KeySchema:
        - AttributeName: "PunchClock"
          KeyType: "HASH"
        - AttributeName: "Updated"
          KeyType: "RANGE"
      AttributeDefinitions:
        - AttributeName: "PunchClock"
          AttributeType: "S"
        - AttributeName: "Updated"
          AttributeType: "N"
      BillingMode: "PAY_PER_REQUEST"
  DDBWorkLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - "WorkLog${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
      KeySchema:
        - AttributeName: "PunchClock"
          KeyType: "HASH"
        - AttributeName: "Started"
          KeyType: "RANGE"
      AttributeDefinitions:
        - AttributeName: "PunchClock"
          AttributeType: "S"
        - AttributeName: "Started"
          AttributeType: "N"
      BillingMode: "PAY_PER_REQUEST"
Outputs:
  StackArn:
    Export:
      Name: !Sub
        - "DataStackArn${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
    Description: "The ARN of this stack for CodePipeline to reference to update"
    Value: !Ref "AWS::StackId"
  StackName:
    Export:
      Name: !Sub
        - "DataStackName${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
    Description: "The name of this stack for CodePipeline to reference to update"
    Value: !Ref "AWS::StackName"
