Parameters:
  DeploymentPhase:
    Type: "String"
    Default: "Development"
    AllowedValues:
      - "Development"
      - "Beta"
      - "Pre-Production"
      - "Production"
    Description: >
      Deployment phases - 
      Development is for testing changes before commit and stack changes are 
      run manually through Console or CLI; 
      Beta is used for automated testing of changes before committing to main; 
      Pre-Production is verification after pushing to main; 
      Production is the final deployment
Mappings:
  DeploymentPhaseProperties:
    Development:
      ResourceSuffix: "-dev"
      CodeBranch: "dev"
    Beta:
      ResourceSuffix: "-beta"
      CodeBranch: "beta"
    Pre-Production:
      ResourceSuffix: "-preprod"
      CodeBranch: "preprod"
    Production:
      ResourceSuffix: ""
      CodeBranch: "main"
  AccountUniqueIdentifiers:
    033566624584:
      GitHubConnectionArn: "arn:aws:codestar-connections:us-west-2:033566624584:connection/1d078144-f66f-45cb-ab3a-f4215e2c828a"
Resources:
  S3ArtifactsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "Private"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: !Sub
        - "mwtaylor.punch-clock.pipeline-artifacts${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
  CloudWatchLogGroupBuilds:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/codebuild/${CodeBuild}"
  IAMCodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub
        - "CodeBuildPunchClock${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
      Description: "Role for CodeBuild to build Punch Clock"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "CodeBuildPunchClock"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "codecommit:GitPull"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:GetObject"
                Resource: !Join
                  - "/"
                  - - !GetAtt "S3ArtifactsBucket.Arn"
                    - "*"
  IAMPipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub
        - "CodePipelinePunchClock${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
      Description: "Role for CodePipeline to use for the main Punch Clock pipeline"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "CodePipelinePunchClock"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "codestar-connections:UseConnection"
                Resource: !FindInMap
                  - "AccountUniqueIdentifiers"
                  - !Ref "AWS::AccountId"
                  - "GitHubConnectionArn"
              - Effect: "Allow"
                Action:
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuilds"
                Resource:
                  !GetAtt "CodeBuild.Arn"
              - Effect: "Allow"
                Action:
                  - "s3:ListBucket"
                Resource: !GetAtt "S3ArtifactsBucket.Arn"
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:GetObject"
                Resource: !Join
                  - "/"
                  - - !GetAtt "S3ArtifactsBucket.Arn"
                    - "*"
              - Effect: "Allow"
                Action:
                  - "cloudformation:DescribeStacks"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "cloudformation:UpdateStack"
                Resource:
                  "Fn::ImportValue":
                    !Sub
                    - "DataStackArn${Suffix}"
                    - Suffix: !FindInMap
                        - "DeploymentPhaseProperties"
                        - !Ref "DeploymentPhase"
                        - "ResourceSuffix"
              - Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource:
                  "Fn::ImportValue":
                    !Sub
                    - "IAMDataStackUpdateRoleArn${Suffix}"
                    - Suffix: !FindInMap
                        - "DeploymentPhaseProperties"
                        - !Ref "DeploymentPhase"
                        - "ResourceSuffix"
  IAMBuildLogsPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub
        - "CodeBuildPunchClockLogs${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
      Roles:
        - !Ref "IAMCodeBuildRole"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: !GetAtt "CloudWatchLogGroupBuilds.Arn"
  CodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Sub
        - "PunchClockBuild${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
      Artifacts:
        Type: "CODEPIPELINE"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-aarch64-standard:2.0"
        Type: "ARM_CONTAINER"
      ServiceRole: !GetAtt "IAMCodeBuildRole.Arn"
      Source:
        Type: "CODEPIPELINE"
      TimeoutInMinutes: 5
  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub
        - "PunchClock${Suffix}"
        - Suffix: !FindInMap
            - "DeploymentPhaseProperties"
            - !Ref "DeploymentPhase"
            - "ResourceSuffix"
      ArtifactStore:
        Type: "S3"
        Location: !Ref "S3ArtifactsBucket"
      RoleArn: !GetAtt "IAMPipelineRole.Arn"
      Stages:
        - Name: "Source"
          Actions:
            - Name: "GitHubSource"
              ActionTypeId:
                Category: "Source"
                Owner: "AWS"
                Provider: "CodeStarSourceConnection"
                Version: 1
              Configuration:
                ConnectionArn: !FindInMap
                  - "AccountUniqueIdentifiers"
                  - !Ref "AWS::AccountId"
                  - "GitHubConnectionArn"
                FullRepositoryId: "mwtaylor/PunchClock"
                BranchName: !FindInMap
                  - "DeploymentPhaseProperties"
                  - !Ref "DeploymentPhase"
                  - "CodeBranch"
              OutputArtifacts:
                - Name: "PunchClockSource"
        - Name: "Build"
          Actions:
            - Name: "Build"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: 1
              Configuration:
                ProjectName: !Ref "CodeBuild"
              InputArtifacts:
                - Name: "PunchClockSource"
        - Name: "CloudFormation"
          Actions:
            - Name: "DataStack"
              ActionTypeId:
                Category: Deploy
                Owner: "AWS"
                Provider: "CloudFormation"
                Version: 1
              Configuration:
                StackName:
                  "Fn::ImportValue":
                    !Sub
                    - "DataStackName${Suffix}"
                    - Suffix: !FindInMap
                        - "DeploymentPhaseProperties"
                        - !Ref "DeploymentPhase"
                        - "ResourceSuffix"
                ActionMode: "CREATE_UPDATE"
                Capabilities: "CAPABILITY_NAMED_IAM"
                RoleArn:
                  "Fn::ImportValue":
                    !Sub
                    - "IAMDataStackUpdateRoleArn${Suffix}"
                    - Suffix: !FindInMap
                        - "DeploymentPhaseProperties"
                        - !Ref "DeploymentPhase"
                        - "ResourceSuffix"
                TemplatePath: "PunchClockSource::DataStack.yaml"
              InputArtifacts:
                - Name: "PunchClockSource"
