AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "WorkManagement serverless application and API"
Globals:
  Function:
    Timeout: 3
Resources:
  StartWorkFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "app/"
      Handler: "handler.start_work_handler"
      Runtime: "ruby2.7"
      Architectures:
        - "x86_64"
      MemorySize: 128
